[package]
name = "aerospike-client-rust-benchmark"
version = "0.0.1"
description = "Benchmark suite for the Aerospike Rust client"
authors = ["Jan Hecking <jhecking@netgaroo.com>"]
homepage = "https://www.aerospike.com/"
repository = "https://github.com/aerospike/aerospike-client-rust/"
license = "Apache-2.0"

[dependencies]
clap = "2.20"
log = "0.3"
env_logger = "0.3"
aerospike = { path = "../.." }

[[bin]]
name = "benchmark"
